// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lighting.proto

package org.DS.xinqipeiproject.SmartOfficeGRPC;

public interface booleanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOfficeGRPC.booleanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool msg = 2;</code>
   */
  boolean getMsg();
}
