// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Radiators.proto

package org.DS.xinqipeiproject.SmartOfficeGRPC;

public interface booleanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOfficeGRPC.booleanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool msg = 2;</code>
   */
  boolean getMsg();
}
