// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Securitycamera.proto

package org.DS.xinqipeiproject.SmartOfficeGRPC;

public interface cameraResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartFarmingGRPC.cameraResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string aname = 4;</code>
   */
  java.lang.String getAname();
  /**
   * <code>string aname = 4;</code>
   */
  com.google.protobuf.ByteString
      getAnameBytes();

  /**
   * <code>string status = 5;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string cam = 6;</code>
   */
  java.lang.String getCam();
  /**
   * <code>string cam = 6;</code>
   */
  com.google.protobuf.ByteString
      getCamBytes();

  /**
   * <code>int32 volume = 7;</code>
   */
  int getVolume();
}
