// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ComputerControlSystem.proto

package org.DS.xinqipeiproject.SmartOfficeGRPC;

public interface computercontrolsystemResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartFarmingGRPC.computercontrolsystemResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string aname = 4;</code>
   */
  java.lang.String getAname();
  /**
   * <code>string aname = 4;</code>
   */
  com.google.protobuf.ByteString
      getAnameBytes();

  /**
   * <code>string status = 5;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 volume = 6;</code>
   */
  int getVolume();
}
