// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Radiators.proto

package org.DS.xinqipeiproject.SmartOfficeGRPC;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOfficeGRPC.Empty)
    com.google.protobuf.MessageOrBuilder {
}
