// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lighting.proto

package org.DS.xinqipeiproject.SmartOfficeGRPC;

public interface lightingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOfficeGRPC.lightingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string aname = 4;</code>
   */
  java.lang.String getAname();
  /**
   * <code>string aname = 4;</code>
   */
  com.google.protobuf.ByteString
      getAnameBytes();

  /**
   * <code>string status = 5;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 brightness = 6;</code>
   */
  int getBrightness();
}
