// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Radiators.proto

package org.DS.xinqipeiproject.SmartOfficeGRPC;

public interface radiatorsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOfficeGRPC.radiatorsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string radname = 4;</code>
   */
  java.lang.String getRadname();
  /**
   * <code>string radname = 4;</code>
   */
  com.google.protobuf.ByteString
      getRadnameBytes();

  /**
   * <code>string status = 5;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 temperature = 6;</code>
   */
  int getTemperature();

  /**
   * <code>int32 fan = 7;</code>
   */
  int getFan();
}
