// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Camera.proto

package org.DS.xinqipeiproject.SmartOfficeGRPC;

public final class SecuritycameraServiceImpl {
  private SecuritycameraServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOfficeGRPC_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOfficeGRPC_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOfficeGRPC_stringRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOfficeGRPC_stringRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOfficeGRPC_stringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOfficeGRPC_stringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOfficeGRPC_booleanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOfficeGRPC_booleanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOfficeGRPC_booleanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOfficeGRPC_booleanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOfficeGRPC_valueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOfficeGRPC_valueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOfficeGRPC_valueResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOfficeGRPC_valueResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOfficeGRPC_cameraResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOfficeGRPC_cameraResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Camera.proto\022\017SmartOfficeGRPC\"\007\n\005Empty" +
      "\"\035\n\rstringRequest\022\014\n\004text\030\001 \001(\t\"\036\n\016strin" +
      "gResponse\022\014\n\004text\030\001 \001(\t\"\035\n\016booleanReques" +
      "t\022\013\n\003msg\030\002 \001(\010\"\036\n\017booleanResponse\022\013\n\003msg" +
      "\030\002 \001(\010\"\036\n\014valueRequest\022\016\n\006length\030\003 \001(\005\"\037" +
      "\n\rvalueResponse\022\016\n\006length\030\003 \001(\005\"N\n\016camer" +
      "aResponse\022\r\n\005aname\030\004 \001(\t\022\016\n\006status\030\005 \001(\t" +
      "\022\013\n\003cam\030\006 \001(\t\022\020\n\010distance\030\007 \001(\0052\254\003\n\025Secu" +
      "ritycameraService\022H\n\013initialItem\022\026.Smart" +
      "OfficeGRPC.Empty\032\037.SmartOfficeGRPC.camer" +
      "aResponse\"\000\022S\n\014changeCamera\022\036.SmartOffic" +
      "eGRPC.stringRequest\032\037.SmartOfficeGRPC.st" +
      "ringResponse\"\0000\001\022Q\n\014changeVolume\022\035.Smart" +
      "OfficeGRPC.valueRequest\032\036.SmartOfficeGRP" +
      "C.valueResponse\"\0000\001\022L\n\005onOff\022\037.SmartOffi" +
      "ceGRPC.booleanRequest\032 .SmartOfficeGRPC." +
      "booleanResponse\"\000\022S\n\016changeItemName\022\036.Sm" +
      "artOfficeGRPC.stringRequest\032\037.SmartOffic" +
      "eGRPC.stringResponse\"\000BE\n&org.DS.xinqipe" +
      "iproject.SmartOfficeGRPCB\031Securitycamera" +
      "ServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartOfficeGRPC_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartOfficeGRPC_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOfficeGRPC_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_SmartOfficeGRPC_stringRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartOfficeGRPC_stringRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOfficeGRPC_stringRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_SmartOfficeGRPC_stringResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SmartOfficeGRPC_stringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOfficeGRPC_stringResponse_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_SmartOfficeGRPC_booleanRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SmartOfficeGRPC_booleanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOfficeGRPC_booleanRequest_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_SmartOfficeGRPC_booleanResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SmartOfficeGRPC_booleanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOfficeGRPC_booleanResponse_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_SmartOfficeGRPC_valueRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SmartOfficeGRPC_valueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOfficeGRPC_valueRequest_descriptor,
        new java.lang.String[] { "Length", });
    internal_static_SmartOfficeGRPC_valueResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_SmartOfficeGRPC_valueResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOfficeGRPC_valueResponse_descriptor,
        new java.lang.String[] { "Length", });
    internal_static_SmartOfficeGRPC_cameraResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_SmartOfficeGRPC_cameraResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOfficeGRPC_cameraResponse_descriptor,
        new java.lang.String[] { "Aname", "Status", "Cam", "Distance", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
