// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Securitycamera.proto

package org.DS.xinqipeiproject.SmartOfficeGRPC;

public interface valueResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartFarmingGRPC.valueResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 3;</code>
   */
  int getLength();
}
