// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Radiators.proto

package org.DS.gerryproject.SmartFarmingGRPC;

public interface booleanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartFarmingGRPC.booleanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool msg = 2;</code>
   */
  boolean getMsg();
}
