// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Radiators.proto

package org.DS.gerryproject.SmartFarmingGRPC;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartFarmingGRPC.Empty)
    com.google.protobuf.MessageOrBuilder {
}
