// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Radiators.proto

package org.DS.gerryproject.SmartFarmingGRPC;

public interface valueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartFarmingGRPC.valueRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 3;</code>
   */
  int getLength();
}
